"""Data models for Notion API responses and requests."""

from .responses import (
    NotionUser,
    NotionWorkspace,
    NotionDatabase,
    NotionPage,
    NotionBlock,
    NotionProperty,
    NotionRichText,
    NotionFile,
    NotionPaginatedResponse,
    NotionDatabaseQuery,
    NotionDatabaseQueryResponse,
    validate_notion_response,
    validate_paginated_response,
)

from .properties import (
    PropertyType,
    TitleProperty,
    RichTextProperty,
    NumberProperty,
    SelectProperty,
    MultiSelectProperty,
    DateProperty,
    PeopleProperty,
    FilesProperty,
    CheckboxProperty,
    URLProperty,
    EmailProperty,
    PhoneProperty,
    FormulaProperty,
    RelationProperty,
    RollupProperty,
    CreatedTimeProperty,
    CreatedByProperty,
    LastEditedTimeProperty,
    LastEditedByProperty,
    StatusProperty,
    create_property_value,
    parse_property_value,
)

__all__ = [
    # Response models
    "NotionUser",
    "NotionWorkspace",
    "NotionDatabase",
    "NotionPage",
    "NotionBlock",
    "NotionProperty",
    "NotionRichText",
    "NotionFile",
    "NotionPaginatedResponse",
    "NotionDatabaseQuery",
    "NotionDatabaseQueryResponse",
    "validate_notion_response",
    "validate_paginated_response",
    # Property models
    "PropertyType",
    "TitleProperty",
    "RichTextProperty",
    "NumberProperty",
    "SelectProperty",
    "MultiSelectProperty",
    "DateProperty",
    "PeopleProperty",
    "FilesProperty",
    "CheckboxProperty",
    "URLProperty",
    "EmailProperty",
    "PhoneProperty",
    "FormulaProperty",
    "RelationProperty",
    "RollupProperty",
    "CreatedTimeProperty",
    "CreatedByProperty",
    "LastEditedTimeProperty",
    "LastEditedByProperty",
    "StatusProperty",
    "create_property_value",
    "parse_property_value",
]
